source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

use_frameworks!


target 'StylingKitThemes_Tests', :exclusive => true do
  # pod "StylingKitThemes/blue", :path => "../"
  pod "StylingKitThemes/blue", :git => "../"

  
end
