# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
rvm: 2.2 # top most supported by CocoaPods, required 2.2.2 because of 'activesupport' dependency

cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm list known
- gem install cocoapods --version 0.39.0 # Since Travis is not always on latest version
- pod _0.39.0_ install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/StylingKitThemes.xcworkspace -scheme StylingKitThemes-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
