#!/usr/bin/env bash

set -e
set -x

THEME_NAME=${1:-"blue"}

COLOR_NC='\033[0m' # No Color
COLOR_RED='\033[0;31m'

if [ -z $(which sass) ] ;then
	echo -e "$COLOR_RED'sass' compiler not found. Please install using 'gem install sass'$COLOR_RED"
	exit 1
fi

THEME_ROOT="$(dirname $0)/../$THEME_NAME"

if [[ -z $TARGET_BUILD_DIR || -z $CONTENTS_FOLDER_PATH ]] ;then
	OUTPUT_PATH="$THEME_ROOT/css/default.css"
else
	OUTPUT_PATH="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/default.css"
fi

mkdir -p "$(dirname $OUTPUT_PATH)"
sass "$THEME_ROOT/scss/default.scss" "$OUTPUT_PATH"
